db:
  name: zabbix-db
  image:
    repository: gitlab-emea.ubisoft.org:4567/monitoring/zbx/zbx-db-tsdb
    tag: latest
    pullPolicy: Always

  replicaCount: 1
  service:
    name: postgres
    type: NodePort
    servicePort: 5432

  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 8Gi

  persistence:
    enabled: true
    size: 8Gi
    existingClaim:
    accessMode: ReadWriteOnce
    storageClassName: zone1

  pgsql:
    user: "zabbix"
    pass: "zabbix"

  env:
    initdata: local
    raw: 3
    trend: 24

srv:
  name: zabbix-srv
  image:
    repository: gitlab-emea.ubisoft.org:4567/monitoring/zbx/zbx-server
    tag: 4.0.3-json
    pullPolicy: Always

  enabled: true
  replicaCount: 1
  service:
    name: zbx-trapper
    type: NodePort
    servicePort: 10051

  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 2Gi

web:
  name: zabbix-web
  image:
    repository: gitlab-emea.ubisoft.org:4567/monitoring/zbx/zbx-web
    tag: latest
    pullPolicy: Always

  enabled: true
  replicaCount: 2
  service:
    name: http
    type: ClusterIP
    servicePort: 80
    ssl: false
    # nodePort:

  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 2Gi

  ingress:
    enabled: true
    paths:
      - "/"
    hosts:
      - xip.io
    annotations:
    tls:

## Create a kube-state-metrics deployment
## ref: https://github.com/kubernetes/charts/tree/master/stable/kube-state-metrics
deployKubeStateMetrics: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
