db:
  enabled: true
  name: zabbix-db
  image:
    repository: gitlab-emea.ubisoft.org:4567/monitoring/zbx/zbx-db-tsdb
    tag: latest
    pullPolicy: Always

  replicaCount: 1
  service:
    name: postgres
    type: NodePort
    port: 5432

  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 8Gi

  persistence:
    enabled: true
    size: 8Gi
    existingClaim:
    accessMode: ReadWriteOnce
    storageClassName: zone1

  pgsql:
    user: "zabbix"
    pass: "zabbix"

  env:
    initdata: local
    raw: 3
    trend: 24

srv:
  enabled: true
  name: zabbix-srv
  image:
    repository: gitlab-emea.ubisoft.org:4567/monitoring/zbx/zbx-server
    tag: 4.0.3-json
    pullPolicy: Always

  replicaCount: 1
  service:
    name: zbx-trapper
    type: NodePort
    port: 10051

  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 2Gi

  # Custom Zabbix Server configuration files used to override default settings
  configurationFiles:
    zabbix_server.conf: |-
      # Main
      ListenPort=10051
      LogType=system
      LogFile=/var/log/zabbix/zabbix_server.log
      LogFileSize=10
      DebugLevel=3
      PidFile=/var/run/zabbix/zabbix_server.pid

      # Database
      DBHost={{ .Values.srv.name }}
      DBName=zabbix
      DBUser={{ .Values.db.pgsql.user }}
      DBPassword={{ .Values.db.pgsql.pass }}
      DBPort={{ .Values.db.service.port }}

      # Processes
      StartPollers=30
      StartIPMIPollers=10
      StartPollersUnreachable=20
      StartTrappers=60
      StartPingers=20
      StartDiscoverers=3
      StartHTTPPollers=5
      StartTimers=10
      StartEscalators=3
      # StartProxyPollers=1
      # ProxyConfigFrequency=3600
      # ProxyDataFrequency=1
      # JavaGateway=
      # JavaGatewayPort=10052
      # StartJavaPollers=0
      #StartVMwareCollectors=4

      # Tuning
      CacheSize=3G
      CacheUpdateFrequency=120
      StartDBSyncers=6
      HistoryCacheSize=512M
      HistoryIndexCacheSize=128M
      TrendCacheSize=512M
      ValueCacheSize=512M
      #VMwareCacheSize=128M
      Timeout=15
      TrapperTimeout=300
      UnreachablePeriod=45
      UnavailableDelay=60
      UnreachableDelay=15
      LogSlowQueries=3000

      # Paths
      AlertScriptsPath=/usr/lib/zabbix/alertscripts
      ExternalScripts=/usr/lib/zabbix/externalscripts
      Include=/etc/zabbix/zabbix_server.conf.d/*.conf
      LoadModulePath=/usr/lib/zabbix/modules
      FpingLocation=/usr/sbin/fping


web:
  enabled: true
  name: zabbix-web
  image:
    repository: gitlab-emea.ubisoft.org:4567/monitoring/zbx/zbx-web
    tag: latest
    pullPolicy: Always

  replicaCount: 2
  service:
    name: http
    type: ClusterIP
    port: 80
    ssl: false

  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 2Gi

  ingress:
    enabled: true
    paths:
      - "/"
    hosts:
      - xip.io
    annotations:
    tls:

## Create a kube-state-metrics deployment
## ref: https://github.com/kubernetes/charts/tree/master/stable/kube-state-metrics
deployKubeStateMetrics: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
