apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  labels:
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    app.kubernetes.io/instance: {{ .Values.db.name }}
    app.kubernetes.io/release: {{ .Release.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zabbix.name" . }}
      app.kubernetes.io/instance: {{ .Values.db.name }}
      app.kubernetes.io/release: {{ .Release.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zabbix.name" . }}
        app.kubernetes.io/instance: {{ .Values.db.name }}
        app.kubernetes.io/release: {{ .Release.name }}
    spec:
      containers:
        - name: {{ .Values.db.name }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
          - name: {{ .Values.db.service.name }}
            containerPort: {{ .Values.db.service.port }}
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.db.service.port }}
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: {{ .Values.db.service.port }}
            intialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
          env:
          - name: PGSQL_USER
            value: {{ .Values.db.pgsql.user }}
          - name: PGSQL_PASS
            value: {{ .Values.db.pgsql.pass }}
          - name: ZBX_INITDATA
            value: {{ .Values.db.env.initdata }}
          - name: ZBX_PURGE_RAW
            value: {{ .Values.db.env.raw | quote }}
          - name: ZBX_PURGE_TREND
            value: {{ .Values.db.env.trend | quote }}
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          volumeMounts:
          - name: zbx-db-storage
            mountPath: /var/lib/postgresql/data

      volumes:
      - name: zbx-db-storage
      {{- if .Values.db.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.db.persistence.existingClaim | default (.Values.db.name) }}
      {{- else }}
        emptyDir: {}
      {{- end }}

      restartPolicy: Always
      imagePullSecrets:
      - name: gitlab-emea

      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.srv.name }}
  labels:
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    app.kubernetes.io/instance: {{ .Values.srv.name }}
    app.kubernetes.io/release: {{ .Release.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.srv.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zabbix.name" . }}
      app.kubernetes.io/instance: {{ .Values.srv.name }}
      app.kubernetes.io/release: {{ .Release.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zabbix.name" . }}
        app.kubernetes.io/instance: {{ .Values.srv.name }}
        app.kubernetes.io/release: {{ .Release.name }}
    spec:
      containers:
        - name: {{ .Values.srv.name }}
          image: "{{ .Values.srv.image.repository }}:{{ .Values.srv.image.tag }}"
          imagePullPolicy: {{ .Values.srv.image.pullPolicy }}
          ports:
          - name: {{ .Values.srv.service.name }}
            containerPort: {{ .Values.srv.service.port }}
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.srv.service.port }}
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: {{ .Values.srv.service.port }}
            intialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
          env:
          - name: PGSQL_HOST
            value: {{ .Values.db.name }}
          - name: PGSQL_USER
            value: {{ .Values.db.pgsql.user }}
          - name: PGSQL_PASS
            value: {{ .Values.db.pgsql.pass }}
          resources:
            {{- toYaml .Values.srv.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.srv.configuration }}
          - name: config-storage
            mountPath: /etc/zabbix/zabbix_server.conf
            subPath: zabbix_server.conf
            readOnly: false
          {{- end }}

      {{- if .Values.srv.configuration }}
      volumes:
      - name: config-storage
        configMap:
          name: {{ .Values.srv.name }}
      {{- end }}

      restartPolicy: Always
      imagePullSecrets:
      - name: gitlab-emea

      {{- with .Values.srv.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.srv.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.srv.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}
  labels:
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    app.kubernetes.io/instance: {{ .Values.web.name }}
    app.kubernetes.io/release: {{ .Release.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zabbix.name" . }}
      app.kubernetes.io/instance: {{ .Values.web.name }}
      app.kubernetes.io/release: {{ .Release.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zabbix.name" . }}
        app.kubernetes.io/instance: {{ .Values.web.name }}
        app.kubernetes.io/release: {{ .Release.name }}
    spec:
      containers:
        - name: {{ .Values.web.name }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
          - name: {{ .Values.web.service.name }}
            containerPort: {{ .Values.web.service.port }}
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.service.port }}
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.service.port }}
            intialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
          env:
          - name: ZBX_SRV_HOST
            value: {{ .Values.srv.name }}
          - name: PGSQL_HOST
            value: {{ .Values.db.name }}
          - name: PGSQL_USER
            value: {{ .Values.db.pgsql.user }}
          - name: PGSQL_PASS
            value: {{ .Values.db.pgsql.pass }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}

      restartPolicy: Always
      imagePullSecrets:
      - name: gitlab-emea

    {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
