apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  labels:
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Values.db.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zabbix.name" . }}
      app.kubernetes.io/instance: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zabbix.name" . }}
        app.kubernetes.io/instance: {{ .Values.db.name }}
    spec:
      containers:
        - name: {{ .Values.db.name }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
          - name: {{ .Values.db.service.name }}
            containerPort: {{ .Values.db.service.servicePort }}
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.db.service.servicePort }}
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: {{ .Values.db.service.servicePort }}
            intialDelaySeconds: 30
            periodSeconds: 5
          env:
          - name: PGSQL_USER
            value: {{ .Values.db.pgsql.user }}
          - name: PGSQL_PASS
            value: {{ .Values.db.pgsql.pass }}
          - name: ZBX_INITDATA
            value: {{ .Values.db.env.initdata }}
          - name: ZBX_PURGE_RAW
            value: {{ .Values.db.env.raw }}
          - name: ZBX_PURGE_TREND
            value: {{ .Values.db.env.trend }}

      restartPolicy: Always
      imagePullSecrets:
      - name: gitlab-emea

      resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.srv.name }}
  labels:
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Values.srv.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.srv.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zabbix.name" . }}
      app.kubernetes.io/instance: {{ .Values.srv.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zabbix.name" . }}
        app.kubernetes.io/instance: {{ .Values.srv.name }}
    spec:
      containers:
        - name: {{ .Values.srv.name }}
          image: "{{ .Values.srv.image.repository }}:{{ .Values.srv.image.tag }}"
          imagePullPolicy: {{ .Values.srv.image.pullPolicy }}
          ports:
          - name: {{ .Values.srv.service.name }}
            containerPort: {{ .Values.srv.service.servicePort }}
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.srv.service.servicePort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: {{ .Values.srv.service.servicePort }}
            intialDelaySeconds: 10
            periodSeconds: 5
          env:
          - name: PGSQL_HOST
            value: {{ .Values.db.name }}
          - name: PGSQL_USER
            value: {{ .Values.db.pgsql.user }}
          - name: PGSQL_PASS
            value: {{ .Values.db.pgsql.pass }}

      restartPolicy: Always
      imagePullSecrets:
      - name: gitlab-emea

      resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}
  labels:
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Values.web.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zabbix.name" . }}
      app.kubernetes.io/instance: {{ .Values.web.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zabbix.name" . }}
        app.kubernetes.io/instance: {{ .Values.web.name }}
    spec:
      containers:
        - name: {{ .Values.web.name }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.srv.service.servicePort }}
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            intialDelaySeconds: 10
            periodSeconds: 5
          env:
          - name: ZBX_SRV_HOST
            value: {{ .Values.srv.name }}
          - name: PGSQL_HOST
            value: {{ .Values.db.name }}
          - name: PGSQL_USER
            value: {{ .Values.db.pgsql.user }}
          - name: PGSQL_PASS
            value: {{ .Values.db.pgsql.pass }}

      restartPolicy: Always
      imagePullSecrets:
      - name: gitlab-emea

      resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

