apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  labels:
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    app.kubernetes.io/instance: {{ .Values.db.name }}
    app.kubernetes.io/release: {{ .Release.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - name: {{ .Values.db.service.name }}
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.name }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    app.kubernetes.io/instance: {{ .Values.db.name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.srv.name }}
  labels:
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    app.kubernetes.io/instance: {{ .Values.srv.name }}
    app.kubernetes.io/release: {{ .Release.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.srv.service.type }}
  ports:
    - name: {{ .Values.srv.service.name }}
      port: {{ .Values.srv.service.port }}
      targetPort: {{ .Values.srv.service.name }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    app.kubernetes.io/instance: {{ .Values.srv.name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  labels:
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    app.kubernetes.io/instance: {{ .Values.web.name }}
    app.kubernetes.io/release: {{ .Release.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: {{ .Values.web.service.name }}
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.name }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "zabbix.name" . }}
    app.kubernetes.io/instance: {{ .Values.web.name }}
